# Generated by Django 6.0.5 on 2026-05-11 23:51

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kanmind_app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='boards',
            name='members',
            field=models.ManyToManyField(related_name='board_members', to=settings.AUTH_USER_MODEL),
        ),
    ]
