# Generated by Django 6.0.5 on 2026-05-14 23:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kanmind_app', '0004_remove_tasks_assignee_alter_tasks_reviewer_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='boards',
            name='members',
            field=models.ManyToManyField(related_name='boards_members', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='boards',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='boards_owner', to=settings.AUTH_USER_MODEL),
        ),
    ]
