# Generated by Django 6.0.5 on 2026-05-15 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kanmind_app', '0005_alter_boards_members_alter_boards_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasks',
            name='due_date',
            field=models.DateField(default="2026-12-31"),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tasks',
            name='priority',
            field=models.CharField(choices=[(
                'low', 'low'), ('medium', 'medium'), ('high', 'high')], default='medium', max_length=50),
        ),
        migrations.AlterField(
            model_name='tasks',
            name='status',
            field=models.CharField(choices=[('to-do', 'to-do'), ('in-progress', 'in-progress'),
                                   ('in-review', 'review'), ('done', 'done')], default='to-do', max_length=50),
        ),
    ]
