# Generated by Django 6.0.5 on 2026-05-20 16:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kanmind_app', '0010_alter_tasks_assignee_alter_tasks_reviewer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comments',
            old_name='text',
            new_name='content',
        ),
    ]
