# Generated by Django 6.0.5 on 2026-05-22 10:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kanmind_app', '0011_rename_text_comments_content'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='boards',
            options={'verbose_name_plural': 'Boards'},
        ),
        migrations.AlterModelOptions(
            name='comments',
            options={'verbose_name_plural': 'Comments'},
        ),
        migrations.AlterModelOptions(
            name='tasks',
            options={'verbose_name_plural': 'Tasks'},
        ),
    ]
