# Generated by Django 6.0.5 on 2026-05-23 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kanmind_app', '0012_alter_boards_options_alter_comments_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasks',
            name='status',
            field=models.CharField(choices=[('to-do', 'to do'), ('in-progress', 'in progress'), ('review', 'review'), ('done', 'done')], default='to-do', max_length=50),
        ),
    ]
